package content

import (
	"bytes"
	"fmt"

	"github.com/nboughton/go-roll"
	"github.com/nboughton/swnt/content/format"
)

// Gang with a Body
type Gang struct {
	Name               string
	Organization       string
	Business           string
	ReputationAndRumor string
}

// NewGang with random characteristics
func NewGang() Gang {
	c := Gang{
		Name:               gangTable.name.Roll(),
		Organization:       gangTable.organization.Roll(),
		Business:           gangTable.business.Roll(),
		ReputationAndRumor: gangTable.reputation.Roll(),
	}
	return c
}

// Format returns Gang c formatted as type t
func (c Gang) Format(t format.OutputType) string {
	buf := new(bytes.Buffer)

	fmt.Fprintf(buf, format.Table(t, []string{"Gang", ""}, [][]string{
		{gangTable.name.Name, fmt.Sprintf("%s %s", c.Name, c.Organization)},
		{gangTable.business.Name, c.Business},
		{gangTable.reputation.Name, c.ReputationAndRumor},
	}))

	return buf.String()
}

func (c Gang) String() string {
	return c.Format(format.TEXT)
}

var gangTable = struct {
	name         roll.List
	organization roll.List
	business     roll.List
	reputation   roll.List
}{
	// Name SWN Revised Free Edition p192
	roll.List{
		Name: "Name",
		Items: []string{
            "<planet name>",
            "Abergil",
            "Albanian Boys",
            "Albanian",
            "Almighty Saints",
            "Almighty Vice Lord Nation",
            "Azusa 13",
            "Bahala Na",
            "Baltimore Crew",
            "Bamboo Union",
            "Bandidos",
            "Barrio Azteca",
            "Bastards",
            "Beltrán-Leyva",
            "Big",
            "Bing Kong Tong",
            "Black Dragons",
            "Black Family",
            "Black Guerrilla",
            "Black Hand",
            "Black",
            "Bloods",
            "Bloody Axe",
            "Bloody Knife",
            "Bonanno",
            "Boozefighters",
            "Born to Kill",
            "Bounty Hunter Bloods",
            "Breed",
            "Brother Speed",
            "Brothers'",
            "Bufalino",
            "Cali",
            "Camorra",
            "Caribbean",
            "Chaldean",
            "Chambers Brothers",
            "Chosen Few",
            "Chung Ching Yee",
            "Coffin Cheaters",
            "Cohen",
            "Colombo",
            "Columbia Point Dawgs",
            "Combat 18",
            "Cornbread",
            "Corsican",
            "Crips",
            "DeCavalcante",
            "Dead Man Incorporated",
            "Decepticons",
            "Devils Diciples",
            "Diablos",
            "Dixie",
            "East Asian",
            "East Side",
            "Eastern European",
            "El Forastero",
            "El Monte Flores 13",
            "Errol Flynns",
            "European Kindred",
            "Five Families",
            "Florencia 13",
            "Flying Dragons",
            "Folk Nation",
            "Forty-Two",
            "Four Corner Hustlers",
            "Four Seas",
            "Free Souls",
            "Freight Train Riders of America",
            "Fresno Bulldogs",
            "Friends Stand United",
            "Fullerton Boys, Korean",
            "Galloping Goose",
            "Gambino",
            "Gangster Disciples",
            "Genna",
            "Genovese",
            "Ghetto Brothers",
            "Ghost Shadows, Chinese and Vietnamese",
            "Grape Street",
            "Green Street",
            "Greenwich Village",
            "Gulf",
            "Gustin",
            "Gypsy Jokers",
            "Hammer",
            "Hell's Lovers",
            "Hells Angels",
            "Hidden Valley Kings",
            "Highwaymen",
            "Hip Sing",
            "Hispanic",
            "Hogan",
            "Hop Sing Tong",
            "Illuminary",
            "Imperial Klans",
            "Inagawa-kai",
            "Iron Horsemen",
            "Jackson Street Boys",
            "Jalisco New Generation",
            "Jets",
            "Jheri Curls",
            "Jousters",
            "Juárez",
            "K&A",
            "KUMI 415",
            "Kansas City",
            "Keystone State Skinheads",
            "Killeen",
            "Kkangpae",
            "La Familia Michoacana",
            "La Línea",
            "La Raza Nation",
            "Latin Counts",
            "Latin Eagles",
            "Latin Kings",
            "Logan Heights",
            "Los Angeles",
            "Los Mexicles",
            "Los Solidos",
            "Los Zetas",
            "Lucchese",
            "Lucerne Street Doggz",
            "Magaddino",
            "Maniac Latin",
            "Marielitos",
            "Market Street Commandos",
            "Medellín",
            "Menace of Destruction",
            "Mexican",
            "Mexikanemi",
            "Miami Boys",
            "Mickey Cobras",
            "Mongols",
            "Morello",
            "Mullen",
            "Murder, Inc.",
            "Native Mob",
            "Nazi Lowriders",
            "Ndrangheta",
            "Netas",
            "New Mexican",
            "New Orleans",
            "Nine Trey",
            "No Surrender",
            "North Side",
            "Nuestra Familia",
            "OVS",
            "On Leong",
            "Orchard Park Trailblazers",
            "OutLaw",
            "Outlaws",
            "Ozone Park Boys",
            "Pacific Islander",
            "Pagans",
            "Patriarca",
            "Peckerwood",
            "People Nation",
            "Ping On",
            "Pirus",
            "Playboys",
            "Polish mob",
            "Popes",
            "Port Street",
            "Public Enemy No. 1",
            "Puente 13",
            "Puro Tango Blast",
            "Purple Dragons",
            "Purple Family",
            "Purple Guerrilla",
            "Purple Hand",
            "Purple",
            "Ragen's Colts",
            "Red Dragon",
            "Red Dragons",
            "Red Family",
            "Red Guerrilla",
            "Red Hand",
            "Red",
            "Rochester",
            "Rock Machine",
            "Rollin 60's Neighborhood Crips",
            "Rollin' 30s Harlem Crips",
            "Romanian",
            "Rudaj",
            "Russian",
            "Sacra Corona Unita",
            "Saint Frank",
            "Saint Joseph",
            "Saint Louis",
            "San Francisco",
            "San Jose",
            "Santa Monica 13",
            "Savage Nomads",
            "Savage Skulls",
            "Seattle",
            "Serbian",
            "Sex Money Murda",
            "Sharks",
            "Shower",
            "Sicilian",
            "Simon City Royals",
            "Snakehead",
            "Solntsevskaya Bratva",
            "Somali Outlaws",
            "Sons of Samoa",
            "Sons of Silence",
            "South Side",
            "Southeast Asian",
            "Spanish Cobras",
            "State Line Mob",
            "Suey Sing Association",
            "Sun Yee On",
            "Supreme Team",
            "Sureños",
            "TAP Boyz",
            "Temple Street",
            "Texas Syndicate",
            "The Avenues",
            "The Bugs and Meyer Mob",
            "Tiny Rascal",
            "Tong",
            "Tongan Crip",
            "Toonport Rifa 13",
            "Trafficante",
            "Triad",
            "Trinitario",
            "Ukrainian",
            "Unione Corse",
            "United Blood Nation",
            "Vagos",
            "Valley",
            "Varrio Nuevo Estrada",
            "Vatos Locos",
            "Velentzas",
            "Venice 13",
            "Volksfront",
            "Wah Ching",
            "Wah Kee",
            "Warlocks ",
            "West Asian",
            "West Side",
            "Westies",
            "Westmob",
            "Westside Locos 13",
            "White Fence",
            "White Hand",
            "Winter Hill",
            "Wo Hop To",
            "Wo Shing Wo",
            "Yakuza",
            "Yamaguchi-gumi",
            "Yardies",
            "Young Boys",
            "Zoe Pound",
		},
	},

	// Organization SWN Revised Free Edition p192
	roll.List{
		Name: "Organization",
		Items: []string{
            "",
            "",
            "Alliance",
            "Association",
            "Band",
            "Cartel",
            "Circle",
            "Clan",
            "Club",
            "Cooperative",
            "Crew",
            "Disciples",
            "Enterprises",
            "Faction",
            "Familia",
            "Group",
            "Mafia",
            "Mob",
            "Nation",
            "Organization",
            "Outfit",
            "Pact",
            "Partnership",
            "Posse",
            "Social Club",
            "Society",
            "Sodality",
            "Syndicate",
            "Union",
            "Unity",
            "Zaibatsu",
		},
	},

	// Business SWN Revised Free Edition p192
	roll.List{
		Name: "Business",
		Items: []string{
            "Arms Dealing",
            "Assassination",
            "Bio Augmentation",
            "Bootlegging",
            "Computer Hacking",
            "Corporate Espionage",
            "Counterfeiting",
            "Electronics",
            "Energy Weapons",
            "Adult Entertainment",
            "Espionage",
            "Fuel Siphoning",
            "Gambling",
            "High End Scrap",
            "Human Trafficking",
            "Proscribed Flora Trafficking",
            "Identity Theft",
            "Illicit Drugs",
            "Liquor",
            "Loan Sharks",
            "Piracy",
            "Protection",
            "Race Fixing",
            "Robbery",
            "Sex Trade",
            "Transport/Hijacking",
            "Vehicle Theft/Chopshop",
		},
	},

	// ReputationAndRumor SWN Revised Free Edition p192
	roll.List{
		Name: "Reputation and Rumors",
		Items: []string{
            "Tied to racial supremacist",
            "Known for gruesome punishments",
			"Reckless with the lives of their members",
			"Have a dark secret about their leaders",
			"Notoriously xenophobic towards aliens",
			"Lost much money to an embezzler who evaded arrest",
			"Reliable and trustworthy goods",
			"Stole a lot of R&D from a rival corporation",
			"They have high-level political connections",
			"They have connections with offworld gangs",
			"Rumored cover-up of a massive industrial accident",
			"The gang leader is dangerously insane",
			"Rumored ties to a eugenics cult",
			"Rumored ties to a religious cult",
			"Said to have a cache of pretech equipment",
			"Possibly teetering on the edge of bankruptcy",
			"Front for a planetary government’s espionage arm",
			"Secretly run by a psychic cabal",
			"Secretly run by local government",
			"Secretly run by local corporation",
			"Secretly run by hostile aliens",
			"Secretly run by an unbraked AI",
		},
	},
}
